# Generated by Django 3.2.23 on 2023-12-25 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20231217_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='course_videos'),
        ),
    ]
